Better indentation

diff --git a/simonpiemu/scripts/checks b/simonpiemu/scripts/checks
--- a/simonpiemu/scripts/checks
+++ b/simonpiemu/scripts/checks
@@ -8,59 +8,59 @@ ARCH=
 
 # Must be root for some ops
 checkRoot() {
-	if [[ $(sudo whoami) != "root" ]]; then
-		echo -e "[$FAIL] Sim-on-Pi will not continue"
-		echo -e "[$FAIL] Please type your user password or run this script as root"
-		exit 1
-	fi
+    if [[ $(sudo whoami) != "root" ]]; then
+        echo -e "[$FAIL] Sim-on-Pi will not continue"
+        echo -e "[$FAIL] Please type your user password or run this script as root"
+        exit 1
+    fi
 }
 
 checkUser() {
-	whoami
+    whoami
 }
 
 checkArch() {
-	case $MODEL in
-		rpi) ARCH="armv6h" ;;
-		rpi-2) ARCH="armv7h" ;;
-		rpi-3) ARCH="aarch64" ;;
-	esac
+    case $MODEL in
+        rpi) ARCH="armv6h" ;;
+        rpi-2) ARCH="armv7h" ;;
+        rpi-3) ARCH="aarch64" ;;
+    esac
 }
 
 finalizeIt() {
-	umountParts
-	umountImg
-	checkQemu
-	if [ "$DOCKER" = "0" ] && [ "$QEMUISRUNNING" = "0" ]; then
-		killNetwork
-	fi
+    umountParts
+    umountImg
+    checkQemu
+    if [ "$DOCKER" = "0" ] && [ "$QEMUISRUNNING" = "0" ]; then
+        killNetwork
+    fi
 }
 
 initChecks() {
-	checkDocker
-	
-	if [ "$SNDARG" != "-i" ]; then
-		CMD=" -initrd $BOOTPATH/initramfs-linux.img"
-	fi
-
-	if [ "$DOCKER" = "0" ]; then
-		checkRoot
-		checkTap
-		createNetwork
-
-		if [ "$MODEL" = "rpi" ]; then
-			NETWORKCMD="$CMD -net nic,macaddr=$(genMAC) -net tap,ifname=$TAP,script=no,downscript=no"
-		else
-			NETWORKCMD="$CMD -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev tap,id=net0,ifname=$TAP,script=no,downscript=no"
-		fi
-
-	else
-
-		if [ "$MODEL" = "rpi" ]; then
-			NETWORKCMD="$CMD -net nic,macaddr=$(genMAC) -net user,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
-		else
-			NETWORKCMD="$CMD -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev user,id=net0,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
-		fi
-	
-	fi
+    checkDocker
+    
+    if [ "$SNDARG" != "-i" ]; then
+        CMD=" -initrd $BOOTPATH/initramfs-linux.img"
+    fi
+    
+    if [ "$DOCKER" = "0" ]; then
+        checkRoot
+        checkTap
+        createNetwork
+        
+        if [ "$MODEL" = "rpi" ]; then
+            NETWORKCMD="$CMD -net nic,macaddr=$(genMAC) -net tap,ifname=$TAP,script=no,downscript=no"
+        else
+            NETWORKCMD="$CMD -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev tap,id=net0,ifname=$TAP,script=no,downscript=no"
+        fi
+        
+    else
+        
+        if [ "$MODEL" = "rpi" ]; then
+            NETWORKCMD="$CMD -net nic,macaddr=$(genMAC) -net user,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
+        else
+            NETWORKCMD="$CMD -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev user,id=net0,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
+        fi
+        
+    fi
 }
diff --git a/simonpiemu/scripts/images b/simonpiemu/scripts/images
--- a/simonpiemu/scripts/images
+++ b/simonpiemu/scripts/images
@@ -4,89 +4,89 @@ ARCHISO="ArchLinuxARM-$MODEL-latest.tar.gz"
 FILES=("$ARCHISO" "$ARCHISO.md5")
 
 integrityCheck() {
-	cd "$SIMONPI/$MODEL" || exit
-
-	if md5sum --status -c "$ARCHISO.md5"; then
-		echo -e "[$PASS] Integrity check successfully completed"
-	else
-		echo -e "[$FAIL] Integrity check failed, please retry to download"
-		purgeEverything
-		exit 1
-	fi
+    cd "$SIMONPI/$MODEL" || exit
+    
+    if md5sum --status -c "$ARCHISO.md5"; then
+        echo -e "[$PASS] Integrity check successfully completed"
+    else
+        echo -e "[$FAIL] Integrity check failed, please retry to download"
+        purgeEverything
+        exit 1
+    fi
 }
 
 downloadArchImage() {
-	for i in "${FILES[@]}"; do
-		if [ -f "$SIMONPI/$MODEL/$i" ]; then
-			echo -e "[$WARN] $i is present";
-		else
-			echo -e "[$PASS] Downloading ..."
-			"$CURL" -# -L -C - "http://os.archlinuxarm.org/os/$i" -o "$SIMONPI/$MODEL/$i"
-		fi
-	done
-
-	integrityCheck
+    for i in "${FILES[@]}"; do
+        if [ -f "$SIMONPI/$MODEL/$i" ]; then
+            echo -e "[$WARN] $i is present";
+        else
+            echo -e "[$PASS] Downloading ..."
+            "$CURL" -# -L -C - "http://os.archlinuxarm.org/os/$i" -o "$SIMONPI/$MODEL/$i"
+        fi
+    done
+    
+    integrityCheck
 }
 
 createArchImg() {
-	GIGA="$1"
-	isaNumber='^[0-9]+$'
-
-	if ! [[ "$GIGA" =~ $isaNumber ]] || [ -z "$GIGA" ]; then
-		echo -e "[$FAIL] Please specify a size in GB"
-		exit 1
-	elif [ "$GIGA" -lt 2 ]; then
-		echo -e "[$FAIL] Please specify a size >= 2 GB"
-		exit 1
-	fi
-
-	checkDeps
-	isMounted
-	downloadArchImage
-
-	if [ -e "$ARCHIMGPATH" ]; then
-		echo -e "[$WARN] An ${ARCHIMGPATH##*/} file already exists. Please delete it"
-		exit 1
-	else
-		echo -e "[$PASS] Creating a $GIGA GB disk image named ${ARCHIMGPATH##*/} ..."
-		$QEMUIMG create -f raw "$ARCHIMGPATH" "$GIGA"G > /dev/null
-		echo -e "[$PASS] Creating partition table on ${ARCHIMGPATH##*/} ..."
-		(echo o; echo n; echo p; echo 1; echo 8192; echo +100M; echo t; echo c; \
-			echo n; echo p; echo 2; echo 8192; echo ; echo ; echo w) | \
-			$FDISK "$ARCHIMGPATH" >/dev/null 2>&1
-	fi
-
-	sync
-	mapImg
-	checkRoot
-	checkLoop
-	mountImg
-	formatLoDevices
-	mountParts
-	echo -e "[$PASS] Extracting $ARCHISO to ${ARCHIMGPATH##*/} ..."
-	sudo "$BSDTAR" --exclude=^boot -xpf "$SIMONPI/$MODEL/$ARCHISO" -C "$ROOTPATH"
-	sudo "$BSDTAR" -xpf "$SIMONPI/$MODEL/$ARCHISO" boot/* -C "$BOOTPATH" > /dev/null 2>&1
-	customContent
-	sync
-	umountParts
-	umountImg
-	sudo chown "$USER:$USER" "$ARCHIMGPATH"
-	echo -e "[$PASS] DONE"
+    GIGA="$1"
+    isaNumber='^[0-9]+$'
+    
+    if ! [[ "$GIGA" =~ $isaNumber ]] || [ -z "$GIGA" ]; then
+        echo -e "[$FAIL] Please specify a size in GB"
+        exit 1
+        elif [ "$GIGA" -lt 2 ]; then
+        echo -e "[$FAIL] Please specify a size >= 2 GB"
+        exit 1
+    fi
+    
+    checkDeps
+    isMounted
+    downloadArchImage
+    
+    if [ -e "$ARCHIMGPATH" ]; then
+        echo -e "[$WARN] An ${ARCHIMGPATH##*/} file already exists. Please delete it"
+        exit 1
+    else
+        echo -e "[$PASS] Creating a $GIGA GB disk image named ${ARCHIMGPATH##*/} ..."
+        $QEMUIMG create -f raw "$ARCHIMGPATH" "$GIGA"G > /dev/null
+        echo -e "[$PASS] Creating partition table on ${ARCHIMGPATH##*/} ..."
+        (echo o; echo n; echo p; echo 1; echo 8192; echo +100M; echo t; echo c; \
+        echo n; echo p; echo 2; echo 8192; echo ; echo ; echo w) | \
+        $FDISK "$ARCHIMGPATH" >/dev/null 2>&1
+    fi
+    
+    sync
+    mapImg
+    checkRoot
+    checkLoop
+    mountImg
+    formatLoDevices
+    mountParts
+    echo -e "[$PASS] Extracting $ARCHISO to ${ARCHIMGPATH##*/} ..."
+    sudo "$BSDTAR" --exclude=^boot -xpf "$SIMONPI/$MODEL/$ARCHISO" -C "$ROOTPATH"
+    sudo "$BSDTAR" -xpf "$SIMONPI/$MODEL/$ARCHISO" boot/* -C "$BOOTPATH" > /dev/null 2>&1
+    customContent
+    sync
+    umountParts
+    umountImg
+    sudo chown "$USER:$USER" "$ARCHIMGPATH"
+    echo -e "[$PASS] DONE"
 }
 
 runCustomImg() {
-	CUSTOMIMG="$1"
-
-	if [ -z "$CUSTOMIMG" ]; then
-		echo -e "[$FAIL] Please specify an image path"
-		exit 1
-	elif [ ! -f "$CUSTOMIMG" ]; then
-		echo -e "[$FAIL] File not found"
-		exit 1
-	elif [ "$(file "$CUSTOMIMG" | cut -d  ' ' -f 2)" != "DOS/MBR" ]; then
-		echo -e "[$FAIL] Please specify a valid disk image"
-		exit 1
-	else
-		echo -e "[$PASS] Running with disk image named ${CUSTOMIMG##*/}"
-	fi
+    CUSTOMIMG="$1"
+    
+    if [ -z "$CUSTOMIMG" ]; then
+        echo -e "[$FAIL] Please specify an image path"
+        exit 1
+        elif [ ! -f "$CUSTOMIMG" ]; then
+        echo -e "[$FAIL] File not found"
+        exit 1
+        elif [ "$(file "$CUSTOMIMG" | cut -d  ' ' -f 2)" != "DOS/MBR" ]; then
+        echo -e "[$FAIL] Please specify a valid disk image"
+        exit 1
+    else
+        echo -e "[$PASS] Running with disk image named ${CUSTOMIMG##*/}"
+    fi
 }
diff --git a/simonpiemu/scripts/storage b/simonpiemu/scripts/storage
--- a/simonpiemu/scripts/storage
+++ b/simonpiemu/scripts/storage
@@ -12,203 +12,203 @@ LENGHT2=
 LOOPFLAG=$(losetup -l | cut -d " " -f 15 | tail -n +2 | head -n +1)
 
 checkFolders() {
-	for i in "${MOUNTFOLDERS[@]}"; do
-		if [ -d "$SIMONPI/$MODEL/$i" ]; then
-			echo -e "[$WARN] $MODEL/$i folder is present"
-		else
-			echo -e "[$PASS] Creating $MODEL/$i folder ..."
-			mkdir -p "$SIMONPI/$MODEL/$i"
-			chown -R "$USER:$USER" "$SIMONPI/$MODEL/$i"
-		fi
-	done
+    for i in "${MOUNTFOLDERS[@]}"; do
+        if [ -d "$SIMONPI/$MODEL/$i" ]; then
+            echo -e "[$WARN] $MODEL/$i folder is present"
+        else
+            echo -e "[$PASS] Creating $MODEL/$i folder ..."
+            mkdir -p "$SIMONPI/$MODEL/$i"
+            chown -R "$USER:$USER" "$SIMONPI/$MODEL/$i"
+        fi
+    done
 }
 
 checkFs() {
-	echo -e "[$PASS] Checking partitions to prevent failures ..."
-	sudo -E "$VFATCHK" -fp "$DEVICE1" > /dev/null 2>&1
-	sudo -E "$EXT4CHK" -fp "$DEVICE2" > /dev/null 2>&1
-	sync
+    echo -e "[$PASS] Checking partitions to prevent failures ..."
+    sudo -E "$VFATCHK" -fp "$DEVICE1" > /dev/null 2>&1
+    sudo -E "$EXT4CHK" -fp "$DEVICE2" > /dev/null 2>&1
+    sync
 }
 
 checkLoop() {
-	DEVICE1=$(sudo -E losetup -f)
-	DEVICE2=/dev/loop$(( ${DEVICE1##*/loop} + 1 ))
-
-	if [ ${DEVICE2##*/loop} -gt 5  ]; then
-		echo -e "[$WARN] You are using more than 3 instances"
-	fi
+    DEVICE1=$(sudo -E losetup -f)
+    DEVICE2=/dev/loop$(( ${DEVICE1##*/loop} + 1 ))
+    
+    if [ ${DEVICE2##*/loop} -gt 5  ]; then
+        echo -e "[$WARN] You are using more than 3 instances"
+    fi
 }
 
 checkMount() {
-	if [ "$SNDARG" = "-c" ]; then
-		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
-			mapImg
-			checkRoot
-			checkLoop
-			mountImg
-			checkFs
-			umountImg
-		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
-			checkRoot
-			checkFs
-			umountImg
-		elif [ $PMOUNTED = "1" ]; then
-			checkRoot
-			umountParts
-			checkFs
-			umountImg
-		else
-			exit 1
-		fi
-	fi
-
-	if [ "$SNDARG" = "-e" ] || [ "$SNDARG" = "-p" ]; then
-		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
-			return
-		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
-			checkRoot
-			umountImg
-		elif [ $PMOUNTED = "1" ]; then
-			checkRoot
-			umountParts
-			umountImg
-		fi
-	fi
-
-	if [ "$SNDARG" = "-m" ]; then
-		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
-			mapImg
-			checkRoot
-			checkLoop
-			mountImg
-			checkFs
-			checkFolders
-			mountParts
-		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
-			checkRoot
-			checkLoop
-			checkFs
-			checkFolders
-			mountParts
-		elif [ $PMOUNTED = "1" ]; then
-			return
-		else
-			exit 1
-		fi
-	fi
-
-	if [ "$SNDARG" = "-r" ] || [ "$SNDARG" = "-i" ]; then
-		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
-			mapImg
-			checkRoot
-			checkLoop
-			mountImg
-			checkFs
-			checkFolders
-			mountParts
-		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
-			checkRoot
-			checkLoop
-			checkFolders
-			mountParts
-		elif [ $PMOUNTED = "1" ]; then
-			return
-		else
-			exit 1
-		fi
-	fi
-
-	if [ "$SNDARG" = "-u" ]; then
-		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
-			echo -e "[$WARN] ${ARCHIMGPATH##*/} disk image not mounted"
-		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
-			checkRoot
-			umountImg
-		elif [ $PMOUNTED = "1" ]; then
-			checkRoot
-			umountParts
-			umountImg
-		else
-			exit 1
-		fi
-	fi
+    if [ "$SNDARG" = "-c" ]; then
+        if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
+            mapImg
+            checkRoot
+            checkLoop
+            mountImg
+            checkFs
+            umountImg
+            elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
+            checkRoot
+            checkFs
+            umountImg
+            elif [ $PMOUNTED = "1" ]; then
+            checkRoot
+            umountParts
+            checkFs
+            umountImg
+        else
+            exit 1
+        fi
+    fi
+    
+    if [ "$SNDARG" = "-e" ] || [ "$SNDARG" = "-p" ]; then
+        if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
+            return
+            elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
+            checkRoot
+            umountImg
+            elif [ $PMOUNTED = "1" ]; then
+            checkRoot
+            umountParts
+            umountImg
+        fi
+    fi
+    
+    if [ "$SNDARG" = "-m" ]; then
+        if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
+            mapImg
+            checkRoot
+            checkLoop
+            mountImg
+            checkFs
+            checkFolders
+            mountParts
+            elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
+            checkRoot
+            checkLoop
+            checkFs
+            checkFolders
+            mountParts
+            elif [ $PMOUNTED = "1" ]; then
+            return
+        else
+            exit 1
+        fi
+    fi
+    
+    if [ "$SNDARG" = "-r" ] || [ "$SNDARG" = "-i" ]; then
+        if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
+            mapImg
+            checkRoot
+            checkLoop
+            mountImg
+            checkFs
+            checkFolders
+            mountParts
+            elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
+            checkRoot
+            checkLoop
+            checkFolders
+            mountParts
+            elif [ $PMOUNTED = "1" ]; then
+            return
+        else
+            exit 1
+        fi
+    fi
+    
+    if [ "$SNDARG" = "-u" ]; then
+        if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
+            echo -e "[$WARN] ${ARCHIMGPATH##*/} disk image not mounted"
+            elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
+            checkRoot
+            umountImg
+            elif [ $PMOUNTED = "1" ]; then
+            checkRoot
+            umountParts
+            umountImg
+        else
+            exit 1
+        fi
+    fi
 }
 
 isMounted() {
-	if [ -n "$CUSTOMIMG" ] && [ "$ARCHIMGPATH" != "$CUSTOMIMG" ]; then
-		ARCHIMGPATH="$CUSTOMIMG"
-	fi
-
-	if mount | grep "$SIMONPI/$MODEL" > /dev/null; then
-		IMGMOUNTED=1
-		PMOUNTED=1
-	elif ! mount | grep "$SIMONPI/$MODEL" > /dev/null && [ -n "${LOOPFLAG}" ]; then
-	 	IMGMOUNTED=1
-	 	PMOUNTED=0
-	elif [ ! -f "$ARCHIMGPATH" ]; then
-		echo -e "[$WARN] No sd image to use on QEMU. Perhaps you have purged ${ARCHIMGPATH##*/}"
-		IMGMOUNTED=2
-		PMOUNTED=2
-	else
-		IMGMOUNTED=0
-		PMOUNTED=0
-	fi
+    if [ -n "$CUSTOMIMG" ] && [ "$ARCHIMGPATH" != "$CUSTOMIMG" ]; then
+        ARCHIMGPATH="$CUSTOMIMG"
+    fi
+    
+    if mount | grep "$SIMONPI/$MODEL" > /dev/null; then
+        IMGMOUNTED=1
+        PMOUNTED=1
+        elif ! mount | grep "$SIMONPI/$MODEL" > /dev/null && [ -n "${LOOPFLAG}" ]; then
+        IMGMOUNTED=1
+        PMOUNTED=0
+        elif [ ! -f "$ARCHIMGPATH" ]; then
+        echo -e "[$WARN] No sd image to use on QEMU. Perhaps you have purged ${ARCHIMGPATH##*/}"
+        IMGMOUNTED=2
+        PMOUNTED=2
+    else
+        IMGMOUNTED=0
+        PMOUNTED=0
+    fi
 }
 
 formatLoDevices() {
-	echo -e "[$PASS] Creating partitions on disk image named ${ARCHIMGPATH##*/} ..."
-	sudo -E "$VFAT" -n boot -F 32 "$DEVICE1" > /dev/null 2>&1
-	sudo -E "$EXT4" -L rootfs "$DEVICE2" > /dev/null 2>&1
-	sync
+    echo -e "[$PASS] Creating partitions on disk image named ${ARCHIMGPATH##*/} ..."
+    sudo -E "$VFAT" -n boot -F 32 "$DEVICE1" > /dev/null 2>&1
+    sudo -E "$EXT4" -L rootfs "$DEVICE2" > /dev/null 2>&1
+    sync
 }
 
 mountParts() {
-	echo -e "[$PASS] Mounting partitions of ${ARCHIMGPATH##*/} ..."
-	sudo -E mount "$DEVICE1" "$BOOTPATH"
-	sudo -E mount "$DEVICE2" "$ROOTPATH"
+    echo -e "[$PASS] Mounting partitions of ${ARCHIMGPATH##*/} ..."
+    sudo -E mount "$DEVICE1" "$BOOTPATH"
+    sudo -E mount "$DEVICE2" "$ROOTPATH"
 }
 
 umountParts() {
-	echo -e "[$PASS] Umounting partitions of ${ARCHIMGPATH##*/} ..."
-	sudo -E umount "$BOOTPATH"
-	sudo -E umount "$ROOTPATH"
+    echo -e "[$PASS] Umounting partitions of ${ARCHIMGPATH##*/} ..."
+    sudo -E umount "$BOOTPATH"
+    sudo -E umount "$ROOTPATH"
 }
 
 listStorage() {
-	checkFolders
-	echo -e "[$WARN] Content of $SIMONPI/$MODEL"
-	ls "$SIMONPI/$MODEL"
+    checkFolders
+    echo -e "[$WARN] Content of $SIMONPI/$MODEL"
+    ls "$SIMONPI/$MODEL"
 }
 
 mapImg() {
-	echo -e "[$PASS] Mapping lenghts of partitions ..."
-	START1=$(fdisk -lo Start "$ARCHIMGPATH" | tail -n 2 | head -n -1)
-	START2=$(fdisk -lo Start "$ARCHIMGPATH" | tail -n 1)
-	LENGTH1=$(fdisk -lo Sectors "$ARCHIMGPATH" | tail -n 2 | head -n -1)
-	LENGHT2=$(fdisk -lo Sectors "$ARCHIMGPATH" | tail -n 1)
+    echo -e "[$PASS] Mapping lenghts of partitions ..."
+    START1=$(fdisk -lo Start "$ARCHIMGPATH" | tail -n 2 | head -n -1)
+    START2=$(fdisk -lo Start "$ARCHIMGPATH" | tail -n 1)
+    LENGTH1=$(fdisk -lo Sectors "$ARCHIMGPATH" | tail -n 2 | head -n -1)
+    LENGHT2=$(fdisk -lo Sectors "$ARCHIMGPATH" | tail -n 1)
 }
 
 mountImg() {
-	echo -e "[$PASS] Mounting disk image named ${ARCHIMGPATH##*/} ..."
-	sudo -E losetup -o $(( START1*512 )) --sizelimit $(( LENGHT1*512 )) \
-		"$DEVICE1" "$ARCHIMGPATH" > /dev/null 2>&1
-	sudo -E losetup -o $(( START2*512 )) --sizelimit $(( LENGHT2*512 )) \
-		"$DEVICE2" "$ARCHIMGPATH" > /dev/null 2>&1
+    echo -e "[$PASS] Mounting disk image named ${ARCHIMGPATH##*/} ..."
+    sudo -E losetup -o $(( START1*512 )) --sizelimit $(( LENGHT1*512 )) \
+    "$DEVICE1" "$ARCHIMGPATH" > /dev/null 2>&1
+    sudo -E losetup -o $(( START2*512 )) --sizelimit $(( LENGHT2*512 )) \
+    "$DEVICE2" "$ARCHIMGPATH" > /dev/null 2>&1
 }
 
 umountImg() {
-	echo -e "[$PASS] Unmounting disk image named ${ARCHIMGPATH##*/} ..."
-	sudo -E losetup -D
+    echo -e "[$PASS] Unmounting disk image named ${ARCHIMGPATH##*/} ..."
+    sudo -E losetup -D
 }
 
 purge () {
-	if [ $IMGMOUNTED != "2" ]; then
-		echo -e "[$PASS] Soft cleaning ..."
-		rm -rf "$ARCHIMGPATH"
-	fi
+    if [ $IMGMOUNTED != "2" ]; then
+        echo -e "[$PASS] Soft cleaning ..."
+        rm -rf "$ARCHIMGPATH"
+    fi
 }
 
 purgeEverything() {
-	echo -e "[$PASS] Hard cleaning ..."
-	rm -rf "${SIMONPI:?}/$MODEL/"
+    echo -e "[$PASS] Hard cleaning ..."
+    rm -rf "${SIMONPI:?}/$MODEL/"
 }
